### ISSUE TITLE
How to send post data value in go-wrk command?

### ISSUE THREAD

**Issue by kumaranvpl** [tsliwowicz/go-wrk#1]
`curl -X POST -d'{"accountID":"1"}' localhost:1234/getInfo`
How am I supposed to send accountID value in go-wrk command for a post request

**Comment by tsliwowicz** [comment]
Currently there's no support for this. Would you like to try to add this and create a pull request? should be fairly straight forward to do it by taking the payload from a file or the command line.

**Comment by kumaranvpl** [comment]
@tsliwowicz I am just a beginner in golang.. I will try...
