### ISSUE TITLE
-f option

### ISSUE THREAD

**Issue by jp557198** [tsliwowicz/go-wrk#10]
Does the -f option call a file with a list of URLs ?
If so, can you provide an brief description on how to 
use the file. As well as an example showing the format of the file ?

I tried using a conventional URL, and go-wrk complained.

http://www.abc.com/

**Comment by tsliwowicz** [comment]
You should use a conventional URL and it would work fine. Currently it assumes the file contains a single URL.

**Comment by tsliwowicz** [comment]
I am going to close the issue. If you provide an example where it does not work, I will re-open. As long as you put in the file a single URL, it works as far as I can see.
