### ISSUE TITLE
bug in header when passing value key1: key2

### ISSUE THREAD

**Issue by jeffotoni** [tsliwowicz/go-wrk#11]
go-wrk -H "Authorization: Basic key1:key2" 

this will bugar because it is doing split with ":" if the header has another ":" error will occur. 
this will bugar because it is doing split with ":" if the header has another ":" error will occur.
Picking up only Key1

received status code 401 from map[Date:[Fr ....

**Comment by tsliwowicz** [comment]
merged a fix
