### ISSUE TITLE
Doesn't support post data?

### ISSUE THREAD

**Issue by ppLorins** [tsliwowicz/go-wrk#16]
The command line has a "-body" parameter, yet the code seems doesn't attach the data to the HTTP request:
![image](https://user-images.githubusercontent.com/5534049/75628775-2a2fcb80-5c17-11ea-9212-6411c09a7c83.png)

req only attaches some header lines before got sent.   So is this sth  that haven't implemented?

**Comment by pin2t** [comment]
Yout should also set an -M option to a POST like so

> ./go-wrk/go-wrk -c 20 -M POST -d 30 -no-c -no-ka --no-vr -body @first.json https://127.0.0.3/f
